# Basic set up for Cargo projects
---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"

  # Maintain dependencies for Cargo
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
