name: Fix release notes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Update release notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release edit jpegxl-src-v0.12.0 \
            --notes-file .github/release-notes/jpegxl-src.md
          gh release edit 'jpegxl-sys-v0.13.0+libjxl-0.12.0' \
            --notes-file .github/release-notes/jpegxl-sys.md
          gh release edit 'jpegxl-rs-v0.15.0+libjxl-0.12.0' \
            --notes-file .github/release-notes/jpegxl-rs.md
